title: Igorski's blog
description: Manuals to untangling software developemnt
author:
  name: Igor Stojanovski
  twitter: igorskiCo
theme: jekyll-theme-minimal

paginate: 5
paginate_path: "/page:num/"
